### ISSUE TITLE
Interesting!

### ISSUE THREAD

**Issue by rayhanadev** [ch1ck3n-byte/replapi2#1]
Kewl, I love that there are so many people making Replit API packages xD. So, are you going to try and use the GraphQL API or just REST API?

**Comment by darkdarcool** [comment]
yeaaaaaa, im interested too! if you need anything from me don't hesitate to contact @ch1ck3n-byte!

**Comment by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa4** [comment]
> Kewl, I love that there are so many people making Replit API packages xD. So, are you going to try and use the GraphQL API or just REST API?

ha i just thought it would be fun (and to use it for my projects)

**Comment by darkdarcool** [comment]
lol nice
